import sys
from pathlib import Path

# Ensure shared package is importable.
_repo_root = Path(__file__).parent.parent.parent
if str(_repo_root) not in sys.path:
    sys.path.insert(0, str(_repo_root))

from shared.data.curriculum_loader import load_curriculum  # noqa: E402


def main():
    root_dir = Path(__file__).parent.parent.parent
    data = load_curriculum(root_dir)
    out_path = root_dir / "docs" / "PHASES.md"

    lines = [
        "# Daskalo Curriculum Books",
        "",
        "This document outlines the strict grammatical progression of the Daskalo application.",
        "It is auto-generated from the per-book YAML files in `shared/data/books/`.",
        "Every chapter generated by the CLI must adhere to the grammar concepts defined here.",
        "Vocabulary is dynamic based on operator topic input, but the underlying structures remain fixed.",
        "",
    ]

    for book in data["books"]:
        lines.append(f"## Book {book['order']}: {book['title']} (Target: {book['level']})")
        lines.append(f"**Goal:** {book['description']}")
        lines.append("")

        for ch in book["chapters"]:
            lines.append(
                f"*   **Chapter {book['order']}.{ch['order']}** (ID: `{ch['id']}`, Length: `{ch['suggested_length']}`)"
            )
            lines.append("    *   **Grammar Concepts:**")
            for g_line in ch["target_grammar"].strip().split("\n"):
                lines.append(f"        * {g_line.strip()}")
            lines.append(f"    *   **Mandatory Vocabulary:** {', '.join(ch['mandatory_vocabulary'])}")
        lines.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(lines))

    print(f"Generated {out_path}")


if __name__ == "__main__":
    main()
