# ---------------------------------------------------------------------------
# Public Assets GCS bucket — serves images and audio generated by content-cli.
# The Angular app loads media directly from this bucket.
# ---------------------------------------------------------------------------

resource "google_storage_bucket" "public_assets" {
  name          = var.public_assets_bucket_name
  location      = var.region
  force_destroy = false

  uniform_bucket_level_access = true

  cors {
    origin          = ["*"]
    method          = ["GET", "HEAD"]
    response_header = ["Content-Type", "Content-Length", "ETag"]
    max_age_seconds = 3600
  }

  depends_on = [google_project_service.apis]
}

# Make all objects in the bucket publicly readable.
resource "google_storage_bucket_iam_member" "public_assets_public_read" {
  bucket = google_storage_bucket.public_assets.name
  role   = "roles/storage.objectViewer"
  member = "allUsers"
}
