# ---------------------------------------------------------------------------
# Public Assets GCS bucket — serves images and audio generated by content-cli.
# The Angular app loads media directly from this bucket.
# ---------------------------------------------------------------------------

resource "google_storage_bucket" "public_assets" {
  name          = var.public_assets_bucket_name
  location      = var.region
  force_destroy = false

  uniform_bucket_level_access = true

  cors {
    origin          = ["*"]
    method          = ["GET", "HEAD"]
    response_header = ["Content-Type", "Content-Length", "ETag"]
    max_age_seconds = 3600
  }

  depends_on = [google_project_service.apis]
}

# ---------------------------------------------------------------------------
# Link the assets bucket to Firebase Storage so the Firebase SDK and
# storage.rules govern client-side read access.
# The GCS SDK (used by content-cli) bypasses these rules and can still write.
# ---------------------------------------------------------------------------
resource "google_firebase_storage_bucket" "public_assets" {
  provider  = google-beta
  project   = var.project_id
  bucket_id = google_storage_bucket.public_assets.id

  depends_on = [google_project_service.apis]
}
